# Crear el archivo
echo '[build]
  base = "Frontend"
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"' > Frontend/netlify.toml

# Agregarlo al commit anterior
git add Frontend/netlify.toml
git commit --amend --no-edit
git push origin frontendproductivo --force